version: 1.3{build}
image: Visual Studio 2019


environment:
  matrix:
  - PlatformToolset: v142

platform:
    - x64
    - Win32

configuration:
    - Release
    #- Debug

build:
    parallel: true                  # enable MSBuild parallel builds
    verbosity: minimal

before_build:
- ps: |
    Write-Output "Configuration: $env:CONFIGURATION"
    Write-Output "Platform: $env:PLATFORM"
    $generator = switch ($env:PLATFORMTOOLSET)
    {
        "v142" {"Visual Studio 16 2019"}
    }

build_script:
- ps: |
    md _build_$env:PLATFORM -Force | Out-Null
    cd _build_$env:PLATFORM
    & cmake -G "$generator" -T"$env:PLATFORMTOOLSET" -A"$env:PLATFORM" -DCMAKE_CONFIGURATION_TYPES="Release" ..
    if ($LastExitCode -ne 0) {
        throw "Exec: $ErrorMessage"
    }
    & cmake --build . --config $env:CONFIGURATION -- /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
    if ($LastExitCode -ne 0) {
        throw "Exec: $ErrorMessage"
    }

after_build:
    - cd "%APPVEYOR_BUILD_FOLDER%"\_build_%platform%\
    - call "%CONFIGURATION%/DSpellCheckTest.exe"
    - ps: >-
        $dspellcheckFileName = "DSpellCheck.$env:PLATFORM.$env:CONFIGURATION.$env:PLATFORMTOOLSET.dll";
        Push-AppveyorArtifact "$env:CONFIGURATION\DSpellCheck.dll" -FileName DSpellCheck.dll

